version: '3'

services:
  backend:
    build: backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app

  postgres:
    image: postgres
    container_name: backend_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
