version: '3'

services:
  backend:
    build: backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app
      - staticfiles:/opt/app/staticfiles

  postgres:
    image: postgres
    container_name: backend_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    build: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/staticfiles
    ports:
      - "80:80"

volumes:
  pgdata:
  staticfiles:

